### PR TITLE
SLING-11283 - Scripting JSP taglib: update to parent 47

### PR DESCRIPTION
**Pull request by apelluru**
- builds were failing
- upgrade to sling 47
- update some unit test dependencies

### CODE REVIEW

**Review by rombert — CHANGES_REQUESTED** [review]
Thanks for the PR @ashokmca07 . It seems that this bundle update causes integration test failures so we can't merge it as-is.

Here's what I did:

- built and installed this bundle ( `mvn clean install` )
- updated https://github.com/apache/sling-org-apache-sling-starter to use the SNAPSHOT version of the bundle

```
diff --git a/src/main/features/scripting.json b/src/main/features/scripting.json
index b160ccb..1444465 100644
--- a/src/main/features/scripting.json
+++ b/src/main/features/scripting.json
@@ -34,7 +34,7 @@
             "start-order":"20"
         },
         {
-            "id":"org.apache.sling:org.apache.sling.scripting.jsp.taglib:2.4.0",
+            "id":"org.apache.sling:org.apache.sling.scripting.jsp.taglib:2.4.1-SNAPSHOT",
             "start-order":"20"
         },
         {
```
- built the resulting starter ( `mvn clean install`)
- executed the Sling Starter ITs from https://github.com/apache/sling-org-apache-sling-launchpad-testing using `mvn clean install`

At the end I get a bunch of failures

> [ERROR] Tests run: 566, Failures: 19, Errors: 0, Skipped: 1

with the errors looking to be related to JSP compilation.

It would be great if you could fix this so I can merge the PR.

Thanks!

**Comment by rombert** [comment]
BTW, I have created an issue for this PR - SLING-11283. Please use "SLING-11283 - Scripting JSP taglib: update to parent 47" as the commit title.

**Comment by apelluru** [comment]
Hi @rombert 
Thanks for the instructions how to test, more useful information for future testing

I have fixed it and verified as per [instructions](https://github.com/apache/sling-org-apache-sling-scripting-jsp-taglib/pull/3#pullrequestreview-953608489) and compared bundle metadata information with old version 2.4.0.
I have attached screenshots for reference purposes  

**With: org.apache.sling:org.apache.sling.scripting.jsp.taglib:2.4.1-SNAPSHOT**

image

**With: org.apache.sling:org.apache.sling.scripting.jsp.taglib:2.4.0**
image

**Comment by joerghoh** [comment]
@ashokmca07 you can use https://github.com/jsedding/osgi-ds-metatype-diff to compare the DS and metatype information of a bundle in different versions.

**Comment by rombert** [comment]
Thanks for the update @ashokmca07 . I noticed that the bundle has a new import on `org.apache.sling.scripting.core.servlet`. Can you please remove it?

**Comment by apelluru** [comment]
Hi @rombert, fixed it.  Could you please take a look again? 

image

**Comment by rombert** [comment]
Thanks for the update @ashokmca07 . There is still one error in the Sling ITs, related to the class that should be embedded:

```
[ERROR] Failures: 
[ERROR]   JspIncludeTest.testVarInclude:248 Expected status 200 for http://localhost:41000/JspIncludeTest/1651239559930/text_b_1651239559934_649376113.html (content=<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head>
<title>500 org/apache/sling/scripting/core/servlet/CaptureResponseWrapper</title>
</head>
<body>
<h1>org/apache/sling/scripting/core/servlet/CaptureResponseWrapper (500)</h1>
<p>The requested URL /JspIncludeTest/1651239559930/text_b_1651239559934_649376113.html resulted in an error in /apps/nt/unstructured/html.jsp.</p>
<h3>Exception:</h3>
<pre>
java.lang.NoClassDefFoundError: org/apache/sling/scripting/core/servlet/CaptureResponseWrapper
	at org.apache.sling.scripting.jsp.taglib.IncludeTagHandler.dispatch(IncludeTagHandler.java:56)
	at org.apache.sling.scripting.jsp.taglib.AbstractDispatcherTagHandler.doEndTag(AbstractDispatcherTagHandler.java:128)
	at org.apache.jsp.apps.nt.unstructured.html__002e__jsp._jspService(html__002e__jsp.java:360)
	at org.apache.sling.scripting.jsp.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:496)
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:445)
	at org.apache.sling.scripting.jsp.JspScriptEngineFactory$JspScriptEngine.callJsp(JspScriptEngineFactory.java:501)
	at org.apache.sling.scripting.jsp.JspScriptEngineFactory$JspScriptEngine.eval(JspScriptEngineFactory.java:586)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:391)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:187)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:494)
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:583)
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:45)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:88)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:283)
	at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:88)
	at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:109)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:84)
	at org.apache.sling.launchpad.testservices.filters.TestFilter.doFilter(TestFilter.java:47)
	at org.apache.sling.launchpad.testservices.filters.SlingFilter.doFilter(SlingFilter.java:22)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78)
	at org.apache.sling.launchpad.testservices.filters.TestFilter.doFilter(TestFilter.java:47)
	at org.apache.sling.launchpad.testservices.filters.NoPropertyFilter.doFilter(NoPropertyFilter.java:22)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:131)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78)
	at com.composum.sling.nodes.mount.remote.RemoteRequestFilter.doFilter(RemoteRequestFilter.java:76)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:151)
	at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:250)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:126)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:86)
	at org.apache.sling.junit.impl.servlet.TestLogServlet$TestNameLoggingFilter.doFilter(TestLogServlet.java:257)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:142)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:131)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:142)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:73)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:142)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.sling.engine.impl.parameters.RequestParameterSupportConfigurer.doFilter(RequestParameterSupportConfigurer.java:67)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:142)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher$1.doFilter(Dispatcher.java:152)
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager$2.doFilter(WhiteboardManager.java:1002)
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:97)
	at org.apache.felix.http.base.internal.handler.PreprocessorHandler.handle(PreprocessorHandler.java:137)
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager$2.doFilter(WhiteboardManager.java:1008)
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager.invokePreprocessors(WhiteboardManager.java:1012)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:94)
	at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.apache.sling.scripting.core.servlet.CaptureResponseWrapper not found by org.apache.sling.scripting.jsp.taglib [196]
	... 86 more
```

**Comment by oliverlietz** [comment]
@ashokmca07 You need to fix instruction for inlining a class, see https://bnd.bndtools.org/instructions/includeresource.html and e.g. `bnd.bnd` file in project `org.apache.sling.jcr.oak.server`.

**Comment by apelluru** [comment]
Thanks for the example @oliverlietz 
Could you please review again @rombert ? Thanks

`[INFO] Running org.apache.sling.launchpad.webapp.integrationtest.scripting.SlingJSPTaglibTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.331 s - in org.apache.sling.launchpad.webapp.integrationtest.scripting.SlingJSPTaglibTest
[INFO] Running org.apache.sling.launchpad.webapp.integrationtest.JspIncludeTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.633 s - in org.apache.sling.launchpad.webapp.integrationtest.JspIncludeTest
[INFO] Running org.apache.sling.launchpad.webapp.integrationtest.VersionParameterTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.063 s - in org.apache.sling.launchpad.webapp.integrationtest.VersionParameterTest`

**Review by rombert — APPROVED** [review]
Looks good, thanks for following-up @ashokmca07 !

**Pull request merged**
